"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.OPERATORS_LINE_PREFIX = exports.UTF16_ENCODING = exports.ENCODINGS_LINE_PREFIX = exports.NETWORK_STATUS_LINE_PREFIX = exports.SIM_CARD_ICC_LINE_PREFIX = exports.ICC_LINE_PREFIX = void 0;
const ICC_LINE_PREFIX = '+CCID:';
exports.ICC_LINE_PREFIX = ICC_LINE_PREFIX;
const SIM_CARD_ICC_LINE_PREFIX = '+ICCID:';
exports.SIM_CARD_ICC_LINE_PREFIX = SIM_CARD_ICC_LINE_PREFIX;
const NETWORK_STATUS_LINE_PREFIX = '+CREG:';
exports.NETWORK_STATUS_LINE_PREFIX = NETWORK_STATUS_LINE_PREFIX;
const ENCODINGS_LINE_PREFIX = '+CSCS:';
exports.ENCODINGS_LINE_PREFIX = ENCODINGS_LINE_PREFIX;
const UTF16_ENCODING = 'UCS2';
exports.UTF16_ENCODING = UTF16_ENCODING;
const OPERATORS_LINE_PREFIX = '+COPS:';
exports.OPERATORS_LINE_PREFIX = OPERATORS_LINE_PREFIX;