export enum MessageType {
    NOTIFY_BOOTING = 'notify-booting',
    NOTIFY_BOOT_DONE = 'notify-boot-done',
    REQUEST_CATALOG = 'request-catalog',
    REQUEST_SIM_DETAILS = 'request-sim-details',
    ANSWER_CATALOG = 'answer-catalog',
    ANSWER_SIM_DETAILS = 'answer-sim-details',
    ANSWER_CATALOG_CONTENT = 'answer-sim-status',
    ANSWER_SIM_DETAILS_CONTENT = 'answer-sim-details-content',
    NOTIFY_UNKNOWN_SIM_EXISTENCE = 'notify-unknown-sim-existence',
    START_SIM_IDENTIFICATION = 'start-sim-id',
    START_SIM_DATA_EDIT = 'start-sim-data-edit',
    NOTIFY_SMS_RECEIVED = 'notify-sms-received',
    NOTIFY_PORT_ACTIVITY_DETECTED = 'notify-port-activity-detected',
    START_FORCE_SIM_OPERATOR = 'start-force-sim-operator',
    STOP_QUESTIONARY = 'stop-questionary',
    FILL_QUESTIONARY = 'fill-questionary',
    SHOW_SIM = 'show-sim',
    HIDE_SIM = 'hide-sim',
    ENABLE_PORT_ACTIVITY_NOTIFICATIONS = 'enable-port-activity-notifications',
    DISABLE_PORT_ACTIVITY_NOTIFICATIONS = 'disable-port-activity-notifications',
    FREE_TEXT_QUESTION = 'free-text-question',
    SINGLE_SELECTION_QUESTION = 'single-selection-question',
    SUCCESS = 'success',
    ERROR = 'error',
}
